Updates travis yml to fix bundler issue
Latest PR resulted in the following error
on travis:

NoMethodError: undefined method `spec' for nil:NilClass

This is caused by an old bundler. Changing
travis to update bundler will hopefully
fix the issue.